"""add status to courses

Revision ID: dcb1274b20e8
Revises: 077100b5b1a6
Create Date: 2026-09-15 23:26:08.443297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb1274b20e8'
down_revision: Union[str, Sequence[str], None] = '077100b5b1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
